#!/usr/bin/env node

/**
 * Clip tagger — a local web UI for tagging clip focus areas and gender.
 *
 * Extends focus-tagger.js with gender tagging (male/female/neutral).
 * Serves a page showing all local clips as videos. Click on the top/middle/bottom
 * third of each video to set its focus. Use M/F/N buttons to set gender.
 * Changes save instantly to clip-tags.json.
 *
 * Usage:
 *   node src/video/clip-tagger.js
 *   # Opens http://localhost:3456 — open in browser
 *
 * Clips are served from the local clips/ directory.
 * Only clips present locally are shown. R2-only clips won't appear until downloaded.
 */

import { createServer } from 'http';
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync, createReadStream, unlinkSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const CLIPS_ROOT = resolve(ROOT, 'clips');
const TAGS_PATH = resolve(ROOT, 'clips/clip-tags.json');
const PORT = 3456;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function loadTags() {
  if (!existsSync(TAGS_PATH)) return {};
  const raw = JSON.parse(readFileSync(TAGS_PATH, 'utf8'));
  return Object.fromEntries(Object.entries(raw).filter(([k]) => !k.startsWith('_')));
}

function saveTags(tags) {
  const out = {
    _comment: 'Per-clip metadata: focus (subtitle position) and gender (person shown). Values: focus=top|center|bottom, gender=male|female|neutral.',
    _usage: 'Generated by clip-tagger.js. Loaded by pickClipsFromPool() at render time.',
    ...Object.fromEntries(Object.entries(tags).sort()),
  };
  writeFileSync(TAGS_PATH, JSON.stringify(out, null, 2) + '\n');
}

function getAllClips() {
  const results = [];
  function walk(dir, rel = '') {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = resolve(dir, entry.name);
      const relPath = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(full, relPath);
      else if (entry.name.endsWith('.mp4') && !entry.name.includes('backup')) {
        results.push({ filename: entry.name, relPath, fullPath: full });
      }
    }
  }
  walk(CLIPS_ROOT);
  return results.sort((a, b) => a.relPath.localeCompare(b.relPath));
}

// ─── HTML UI ──────────────────────────────────────────────────────────────────

function buildHtml(clips, tags) {
  const clipData = clips.map(c => ({
    filename: c.filename,
    relPath: c.relPath,
    focus: tags[c.filename]?.focus || null,
    gender: tags[c.filename]?.gender || null,
  }));

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Clip Tagger — 2Step</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: #111; color: #eee; font-family: system-ui, sans-serif; padding: 16px; }
  h1 { margin-bottom: 4px; font-size: 18px; }
  .subtitle { color: #888; font-size: 13px; margin-bottom: 16px; }
  .stats { background: #1a1a1a; border-radius: 8px; padding: 10px 14px; margin-bottom: 16px; font-size: 13px; display: flex; gap: 20px; flex-wrap: wrap; }
  .stats span { color: #aaa; } .stats strong { color: #eee; }
  .stats .stat-group { display: flex; gap: 12px; align-items: center; }
  .stats .stat-label { color: #666; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; margin-right: 4px; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 14px; }
  .card { background: #1a1a1a; border-radius: 10px; overflow: hidden; border: 2px solid transparent; transition: border-color 0.15s; }
  .card.tagged-top    { border-color: #4a9eff; }
  .card.tagged-center { border-color: #888; }
  .card.tagged-bottom { border-color: #ff7a4a; }
  .label { padding: 6px 8px; font-size: 11px; color: #aaa; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .video-wrap { position: relative; cursor: pointer; background: #000; }
  video { width: 100%; display: block; aspect-ratio: 9/16; object-fit: cover; }
  /* Click zones — invisible overlays on top/middle/bottom thirds */
  .zone { position: absolute; left: 0; right: 0; display: flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; opacity: 0; transition: opacity 0.15s; }
  .zone-top    { top: 0; height: 33.3%; background: rgba(74,158,255,0.35); color: #4a9eff; }
  .zone-center { top: 33.3%; height: 33.3%; background: rgba(180,180,180,0.2); color: #ccc; }
  .zone-bottom { top: 66.6%; height: 33.4%; background: rgba(255,122,74,0.35); color: #ff7a4a; }
  .video-wrap:hover .zone { opacity: 1; }
  .focus-badge { position: absolute; bottom: 6px; right: 6px; padding: 2px 7px; border-radius: 10px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; }
  .badge-top    { background: #4a9eff; color: #000; }
  .badge-center { background: #555; color: #eee; }
  .badge-bottom { background: #ff7a4a; color: #000; }
  .badge-none   { background: #333; color: #777; }
  .gender-badge { position: absolute; bottom: 6px; left: 6px; padding: 2px 7px; border-radius: 10px; font-size: 12px; font-weight: 700; }
  .gender-male    { background: #3b82f6; color: #fff; }
  .gender-female  { background: #ec4899; color: #fff; }
  .gender-neutral { background: #555; color: #eee; }
  .gender-none    { background: #333; color: #777; }
  .gender-buttons { display: flex; gap: 4px; padding: 6px 8px; justify-content: center; }
  .gender-btn { flex: 1; padding: 4px 0; border: 1px solid #333; border-radius: 6px; background: #222; color: #777; font-size: 11px; font-weight: 700; cursor: pointer; text-align: center; transition: all 0.15s; }
  .gender-btn:hover { border-color: #555; color: #aaa; }
  .gender-btn.active-male    { background: #3b82f6; border-color: #3b82f6; color: #fff; }
  .gender-btn.active-female  { background: #ec4899; border-color: #ec4899; color: #fff; }
  .gender-btn.active-neutral { background: #555; border-color: #666; color: #eee; }
  .btn-delete { position: absolute; top: 6px; right: 6px; background: rgba(0,0,0,0.6); border: 1px solid #555; color: #888; width: 22px; height: 22px; border-radius: 50%; font-size: 13px; line-height: 1; cursor: pointer; display: flex; align-items: center; justify-content: center; opacity: 0; transition: opacity 0.15s, color 0.15s, border-color 0.15s; }
  .btn-delete:hover { color: #ff4444; border-color: #ff4444; }
  .video-wrap:hover .btn-delete { opacity: 1; }
  #toast { position: fixed; bottom: 20px; right: 20px; background: #222; border: 1px solid #444; color: #eee; padding: 8px 14px; border-radius: 8px; font-size: 13px; opacity: 0; transition: opacity 0.2s; pointer-events: none; }
  #toast.show { opacity: 1; }
  .legend { display: flex; gap: 12px; margin-bottom: 12px; font-size: 12px; align-items: center; }
  .legend-item { display: flex; align-items: center; gap: 5px; }
  .dot { width: 10px; height: 10px; border-radius: 50%; }
  .pagination { display: flex; align-items: center; gap: 8px; margin-bottom: 16px; }
  .pagination button { background: #1a1a1a; border: 1px solid #333; color: #eee; padding: 5px 14px; border-radius: 6px; cursor: pointer; font-size: 13px; }
  .pagination button:hover:not(:disabled) { background: #2a2a2a; }
  .pagination button:disabled { opacity: 0.3; cursor: default; }
  .pagination .page-info { font-size: 13px; color: #aaa; }
</style>
</head>
<body>
<h1>Clip Tagger</h1>
<p class="subtitle">Click where you want subtitles to appear in each clip. Use M/F/N to tag gender. Saves instantly.</p>

<div class="legend">
  <span style="color:#888">Subtitles at:</span>
  <div class="legend-item"><div class="dot" style="background:#4a9eff"></div> Top of frame</div>
  <div class="legend-item"><div class="dot" style="background:#888"></div> Center of frame</div>
  <div class="legend-item"><div class="dot" style="background:#ff7a4a"></div> Bottom of frame</div>
</div>

<div class="stats">
  <div class="stat-group">
    <span class="stat-label">Focus:</span>
    <div><strong id="stat-focus-tagged">0</strong> <span>tagged</span></div>
    <div><strong id="stat-focus-total">${clips.length}</strong> <span>total</span></div>
    <div><strong id="stat-focus-remaining">0</strong> <span>remaining</span></div>
  </div>
  <div class="stat-group">
    <span class="stat-label">Gender:</span>
    <div><strong id="stat-gender-tagged">0</strong> <span>tagged</span></div>
    <div><strong id="stat-gender-total">${clips.length}</strong> <span>total</span></div>
    <div><strong id="stat-gender-remaining">0</strong> <span>remaining</span></div>
  </div>
  <div style="margin-left:auto; display:flex; gap:14px; align-items:center;">
    <label style="cursor:pointer;user-select:none">
      <input type="checkbox" id="chk-untagged" onchange="toggleFilter()"> Focus untagged only
    </label>
    <label style="cursor:pointer;user-select:none">
      <input type="checkbox" id="chk-gender-untagged" onchange="toggleFilter()"> Gender untagged only
    </label>
  </div>
</div>

<div class="pagination">
  <button id="btn-prev" onclick="goPage(page-1)">&#8592; Prev</button>
  <span class="page-info" id="page-info"></span>
  <button id="btn-next" onclick="goPage(page+1)">Next &#8594;</button>
</div>

<div class="grid" id="grid"></div>
<div id="toast"></div>

<script>
const clips = ${JSON.stringify(clipData)};
const tags = {};
// Build tags lookup from clip data
clips.forEach(c => {
  const entry = {};
  if (c.focus) entry.focus = c.focus;
  if (c.gender) entry.gender = c.gender;
  if (Object.keys(entry).length) tags[c.filename] = entry;
});

const PAGE_SIZE = 20;
let page = 0;
let filterFocusUntagged = false;
let filterGenderUntagged = false;

function visibleClips() {
  let result = clips;
  if (filterFocusUntagged) result = result.filter(c => !tags[c.filename]?.focus);
  if (filterGenderUntagged) result = result.filter(c => !tags[c.filename]?.gender);
  return result;
}

function toggleFilter() {
  filterFocusUntagged = document.getElementById('chk-untagged').checked;
  filterGenderUntagged = document.getElementById('chk-gender-untagged').checked;
  renderPage(0);
}

function toast(msg) {
  const el = document.getElementById('toast');
  el.textContent = msg;
  el.classList.add('show');
  clearTimeout(el._t);
  el._t = setTimeout(() => el.classList.remove('show'), 1800);
}

function updateStats() {
  const focusTagged = clips.filter(c => tags[c.filename]?.focus).length;
  const genderTagged = clips.filter(c => tags[c.filename]?.gender).length;
  document.getElementById('stat-focus-tagged').textContent = focusTagged;
  document.getElementById('stat-focus-remaining').textContent = clips.length - focusTagged;
  document.getElementById('stat-gender-tagged').textContent = genderTagged;
  document.getElementById('stat-gender-remaining').textContent = clips.length - genderTagged;
}

const GENDER_SYMBOLS = { male: '\\u2642', female: '\\u2640', neutral: '\\u26AC' };

async function saveTag(filename, field, value) {
  if (!tags[filename]) tags[filename] = {};
  tags[filename][field] = value;

  await fetch('/save', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ filename, [field]: value }),
  });
}

async function setFocus(filename, focus) {
  await saveTag(filename, 'focus', focus);
  const card = document.querySelector(\`[data-file="\${filename}"]\`);
  if (card) {
    if (filterFocusUntagged) {
      card.querySelector('video')?.pause();
      card.style.transition = 'opacity 0.2s';
      card.style.opacity = '0';
      setTimeout(() => card.remove(), 200);
    } else {
      card.className = \`card tagged-\${focus}\`;
      const badge = card.querySelector('.focus-badge');
      badge.textContent = focus;
      badge.className = \`focus-badge badge-\${focus}\`;
    }
  }
  updateStats();
  toast(\`\${filename} \u2192 focus: \${focus}\`);
}

async function setGender(filename, gender) {
  await saveTag(filename, 'gender', gender);
  const card = document.querySelector(\`[data-file="\${filename}"]\`);
  if (card) {
    if (filterGenderUntagged) {
      card.querySelector('video')?.pause();
      card.style.transition = 'opacity 0.2s';
      card.style.opacity = '0';
      setTimeout(() => card.remove(), 200);
    } else {
      // Update gender badge
      const gBadge = card.querySelector('.gender-badge');
      gBadge.textContent = GENDER_SYMBOLS[gender] || '\\u2014';
      gBadge.className = \`gender-badge gender-\${gender}\`;
      // Update button highlights
      card.querySelectorAll('.gender-btn').forEach(btn => {
        const g = btn.dataset.gender;
        btn.className = \`gender-btn\${g === gender ? ' active-' + g : ''}\`;
      });
    }
  }
  updateStats();
  toast(\`\${filename} \u2192 gender: \${gender}\`);
}

function buildCard(clip) {
  const focus = tags[clip.filename]?.focus || null;
  const gender = tags[clip.filename]?.gender || null;
  const card = document.createElement('div');
  card.className = 'card' + (focus ? \` tagged-\${focus}\` : '');
  card.dataset.file = clip.filename;

  const genderSymbol = gender ? GENDER_SYMBOLS[gender] : '\\u2014';
  const genderClass = gender ? \`gender-\${gender}\` : 'gender-none';

  card.innerHTML = \`
    <div class="label" title="\${clip.relPath}">\${clip.filename.replace('.mp4','')}</div>
    <div class="video-wrap">
      <video src="/clips/\${clip.relPath}" loop muted playsinline preload="metadata"></video>
      <div class="zone zone-top" data-focus="top">Subtitles Top</div>
      <div class="zone zone-center" data-focus="center">Subtitles Center</div>
      <div class="zone zone-bottom" data-focus="bottom">Subtitles Bottom</div>
      <div class="focus-badge \${focus ? 'badge-'+focus : 'badge-none'}">\${focus || '\\u2014'}</div>
      <div class="gender-badge \${genderClass}">\${genderSymbol}</div>
      <button class="btn-delete" title="Delete local file">\\u2715</button>
    </div>
    <div class="gender-buttons">
      <button class="gender-btn\${gender === 'male' ? ' active-male' : ''}" data-gender="male">M</button>
      <button class="gender-btn\${gender === 'female' ? ' active-female' : ''}" data-gender="female">F</button>
      <button class="gender-btn\${gender === 'neutral' ? ' active-neutral' : ''}" data-gender="neutral">N</button>
    </div>
  \`;

  // Play on hover
  const video = card.querySelector('video');
  card.addEventListener('mouseenter', () => video.play());
  card.addEventListener('mouseleave', () => { video.pause(); video.currentTime = 0; });

  // Click zone to set focus
  card.querySelectorAll('.zone').forEach(zone => {
    zone.addEventListener('click', e => {
      e.stopPropagation();
      setFocus(clip.filename, zone.dataset.focus);
    });
  });

  // Gender buttons
  card.querySelectorAll('.gender-btn').forEach(btn => {
    btn.addEventListener('click', e => {
      e.stopPropagation();
      setGender(clip.filename, btn.dataset.gender);
    });
  });

  // Delete local file
  card.querySelector('.btn-delete').addEventListener('click', async e => {
    e.stopPropagation();
    if (!confirm(\`Delete \${clip.filename} from local disk?\`)) return;
    video.pause();
    await fetch('/delete', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ relPath: clip.relPath }),
    });
    card.style.transition = 'opacity 0.2s';
    card.style.opacity = '0';
    setTimeout(() => card.remove(), 200);
    toast(\`Deleted \${clip.filename}\`);
  });

  return card;
}

function renderPage(p) {
  const view = visibleClips();
  const totalPages = Math.max(1, Math.ceil(view.length / PAGE_SIZE));
  page = Math.max(0, Math.min(p, totalPages - 1));
  const start = page * PAGE_SIZE;
  const pageClips = view.slice(start, start + PAGE_SIZE);

  // Pause all playing videos before clearing
  document.querySelectorAll('video').forEach(v => v.pause());

  const grid = document.getElementById('grid');
  grid.innerHTML = '';
  for (const clip of pageClips) grid.appendChild(buildCard(clip));

  document.getElementById('page-info').textContent = view.length === 0
    ? 'All clips tagged!'
    : \`Page \${page + 1} of \${totalPages} (clips \${start + 1}\u2013\${Math.min(start + PAGE_SIZE, view.length)} of \${view.length})\`;
  document.getElementById('btn-prev').disabled = page === 0;
  document.getElementById('btn-next').disabled = page >= totalPages - 1;
  window.scrollTo(0, 0);
  updateStats();
}

function goPage(p) { renderPage(p); }

renderPage(0);
</script>
</body>
</html>`;
}

// ─── Server ───────────────────────────────────────────────────────────────────

const server = createServer((req, res) => {
  // Save tag (focus and/or gender)
  if (req.method === 'POST' && req.url === '/save') {
    let body = '';
    req.on('data', d => body += d);
    req.on('end', () => {
      try {
        const { filename, focus, gender } = JSON.parse(body);
        if (focus && !['top', 'center', 'bottom'].includes(focus)) throw new Error('invalid focus');
        if (gender && !['male', 'female', 'neutral'].includes(gender)) throw new Error('invalid gender');
        if (!focus && !gender) throw new Error('must provide focus or gender');
        const tags = loadTags();
        if (!tags[filename]) tags[filename] = {};
        if (focus) tags[filename].focus = focus;
        if (gender) tags[filename].gender = gender;
        saveTags(tags);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true }));
      } catch (e) {
        res.writeHead(400);
        res.end(e.message);
      }
    });
    return;
  }

  // Delete local file
  if (req.method === 'POST' && req.url === '/delete') {
    let body = '';
    req.on('data', d => body += d);
    req.on('end', () => {
      try {
        const { relPath } = JSON.parse(body);
        const fullPath = resolve(CLIPS_ROOT, relPath);
        if (!fullPath.startsWith(CLIPS_ROOT)) throw new Error('path traversal');
        if (existsSync(fullPath)) unlinkSync(fullPath);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true }));
      } catch (e) {
        res.writeHead(400);
        res.end(e.message);
      }
    });
    return;
  }

  // Serve clips
  if (req.url.startsWith('/clips/')) {
    const relPath = decodeURIComponent(req.url.slice(7));
    const fullPath = resolve(CLIPS_ROOT, relPath);
    // Basic path traversal guard
    if (!fullPath.startsWith(CLIPS_ROOT)) { res.writeHead(403); res.end(); return; }
    if (!existsSync(fullPath)) { res.writeHead(404); res.end(); return; }
    const stat = statSync(fullPath);
    res.writeHead(200, {
      'Content-Type': 'video/mp4',
      'Content-Length': stat.size,
      'Accept-Ranges': 'bytes',
    });
    createReadStream(fullPath).pipe(res);
    return;
  }

  // Main page
  if (req.url === '/' || req.url === '') {
    const clips = getAllClips();
    const tags = loadTags();
    const html = buildHtml(clips, tags);
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(html);
    return;
  }

  res.writeHead(404);
  res.end();
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`Clip tagger running at http://localhost:${PORT}`);
  console.log('Open that URL in your browser.');
  console.log('Hover over a clip to play it, click top/middle/bottom to tag focus.');
  console.log('Use M/F/N buttons below each clip to tag gender.');
  console.log('Changes save instantly to clips/clip-tags.json\n');
  console.log('Press Ctrl+C to stop.');
});
