#!/usr/bin/env node

/**
 * Focus tagger — a local web UI for tagging clip focus areas.
 *
 * Serves a page showing all local clips as videos. Click on the top/middle/bottom
 * third of each video to set its focus. Changes save instantly to focus-overrides.json.
 *
 * Usage:
 *   node src/video/focus-tagger.js
 *   # Opens http://localhost:3456 — open in browser
 *
 * Clips are served from the local clips/ directory.
 * Only clips present locally are shown. R2-only clips won't appear until downloaded.
 */

import { createServer } from 'http';
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync, createReadStream } from 'fs';
import { resolve, dirname, extname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const CLIPS_ROOT = resolve(ROOT, 'clips');
const OVERRIDES_PATH = resolve(ROOT, 'clips/focus-overrides.json');
const PORT = 3456;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function loadOverrides() {
  if (!existsSync(OVERRIDES_PATH)) return {};
  const raw = JSON.parse(readFileSync(OVERRIDES_PATH, 'utf8'));
  return Object.fromEntries(Object.entries(raw).filter(([k]) => !k.startsWith('_')));
}

function saveOverrides(overrides) {
  const out = {
    _comment: 'Maps clip filename (without path) to focus area. Values: top | center | bottom.',
    _usage: 'Generated by focus-tagger.js. Loaded by pickClipsFromPool() at render time.',
    _values: { top: 'subject upper → text bottom', center: 'subject middle → text top (default)', bottom: 'subject lower → text top' },
    ...Object.fromEntries(Object.entries(overrides).sort()),
  };
  writeFileSync(OVERRIDES_PATH, JSON.stringify(out, null, 2) + '\n');
}

function getAllClips() {
  const results = [];
  function walk(dir, rel = '') {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = resolve(dir, entry.name);
      const relPath = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(full, relPath);
      else if (entry.name.endsWith('.mp4') && !entry.name.includes('backup')) {
        results.push({ filename: entry.name, relPath, fullPath: full });
      }
    }
  }
  walk(CLIPS_ROOT);
  return results.sort((a, b) => a.relPath.localeCompare(b.relPath));
}

// ─── HTML UI ──────────────────────────────────────────────────────────────────

function buildHtml(clips, overrides) {
  const clipData = clips.map(c => ({
    filename: c.filename,
    relPath: c.relPath,
    focus: overrides[c.filename] || null,
  }));

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Focus Tagger — 2Step</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: #111; color: #eee; font-family: system-ui, sans-serif; padding: 16px; }
  h1 { margin-bottom: 4px; font-size: 18px; }
  .subtitle { color: #888; font-size: 13px; margin-bottom: 16px; }
  .stats { background: #1a1a1a; border-radius: 8px; padding: 10px 14px; margin-bottom: 16px; font-size: 13px; display: flex; gap: 20px; }
  .stats span { color: #aaa; } .stats strong { color: #eee; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 14px; }
  .card { background: #1a1a1a; border-radius: 10px; overflow: hidden; border: 2px solid transparent; transition: border-color 0.15s; }
  .card.tagged-top    { border-color: #4a9eff; }
  .card.tagged-center { border-color: #888; }
  .card.tagged-bottom { border-color: #ff7a4a; }
  .label { padding: 6px 8px; font-size: 11px; color: #aaa; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .video-wrap { position: relative; cursor: pointer; background: #000; }
  video { width: 100%; display: block; aspect-ratio: 9/16; object-fit: cover; }
  /* Click zones — invisible overlays on top/middle/bottom thirds */
  .zone { position: absolute; left: 0; right: 0; display: flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; opacity: 0; transition: opacity 0.15s; }
  .zone-top    { top: 0; height: 33.3%; background: rgba(74,158,255,0.35); color: #4a9eff; }
  .zone-center { top: 33.3%; height: 33.3%; background: rgba(180,180,180,0.2); color: #ccc; }
  .zone-bottom { top: 66.6%; height: 33.4%; background: rgba(255,122,74,0.35); color: #ff7a4a; }
  .video-wrap:hover .zone { opacity: 1; }
  .focus-badge { position: absolute; bottom: 6px; right: 6px; padding: 2px 7px; border-radius: 10px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; }
  .badge-top    { background: #4a9eff; color: #000; }
  .badge-center { background: #555; color: #eee; }
  .badge-bottom { background: #ff7a4a; color: #000; }
  .badge-none   { background: #333; color: #777; }
  #toast { position: fixed; bottom: 20px; right: 20px; background: #222; border: 1px solid #444; color: #eee; padding: 8px 14px; border-radius: 8px; font-size: 13px; opacity: 0; transition: opacity 0.2s; pointer-events: none; }
  #toast.show { opacity: 1; }
  .legend { display: flex; gap: 12px; margin-bottom: 12px; font-size: 12px; align-items: center; }
  .legend-item { display: flex; align-items: center; gap: 5px; }
  .dot { width: 10px; height: 10px; border-radius: 50%; }
</style>
</head>
<body>
<h1>Focus Tagger</h1>
<p class="subtitle">Click the top / middle / bottom third of each clip to set where the subject is. Saves instantly.</p>

<div class="legend">
  <span style="color:#888">Focus zone:</span>
  <div class="legend-item"><div class="dot" style="background:#4a9eff"></div> Top → text at bottom</div>
  <div class="legend-item"><div class="dot" style="background:#888"></div> Center → text at top (default)</div>
  <div class="legend-item"><div class="dot" style="background:#ff7a4a"></div> Bottom → text at top</div>
</div>

<div class="stats">
  <div><strong id="stat-tagged">0</strong> <span>tagged</span></div>
  <div><strong id="stat-total">${clips.length}</strong> <span>total</span></div>
  <div><strong id="stat-remaining">0</strong> <span>remaining</span></div>
</div>

<div class="grid" id="grid"></div>
<div id="toast"></div>

<script>
const clips = ${JSON.stringify(clipData)};
const overrides = ${JSON.stringify(overrides)};

function toast(msg) {
  const el = document.getElementById('toast');
  el.textContent = msg;
  el.classList.add('show');
  clearTimeout(el._t);
  el._t = setTimeout(() => el.classList.remove('show'), 1800);
}

function updateStats() {
  const tagged = Object.keys(overrides).length;
  document.getElementById('stat-tagged').textContent = tagged;
  document.getElementById('stat-remaining').textContent = clips.length - tagged;
}

async function setFocus(filename, focus) {
  overrides[filename] = focus;
  // Update UI
  const card = document.querySelector(\`[data-file="\${filename}"]\`);
  if (card) {
    card.className = \`card tagged-\${focus}\`;
    const badge = card.querySelector('.focus-badge');
    badge.textContent = focus;
    badge.className = \`focus-badge badge-\${focus}\`;
  }
  updateStats();
  toast(\`\${filename} → \${focus}\`);
  // Save to server
  await fetch('/save', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ filename, focus }),
  });
}

function buildCard(clip) {
  const focus = overrides[clip.filename] || null;
  const card = document.createElement('div');
  card.className = 'card' + (focus ? \` tagged-\${focus}\` : '');
  card.dataset.file = clip.filename;

  card.innerHTML = \`
    <div class="label" title="\${clip.relPath}">\${clip.filename.replace('.mp4','')}</div>
    <div class="video-wrap">
      <video src="/clips/\${clip.relPath}" loop muted playsinline preload="metadata"></video>
      <div class="zone zone-top" data-focus="top">Top</div>
      <div class="zone zone-center" data-focus="center">Center</div>
      <div class="zone zone-bottom" data-focus="bottom">Bottom</div>
      <div class="focus-badge \${focus ? 'badge-'+focus : 'badge-none'}">\${focus || '—'}</div>
    </div>
  \`;

  // Play on hover
  const video = card.querySelector('video');
  card.addEventListener('mouseenter', () => video.play());
  card.addEventListener('mouseleave', () => { video.pause(); video.currentTime = 0; });

  // Click zone to set focus
  card.querySelectorAll('.zone').forEach(zone => {
    zone.addEventListener('click', e => {
      e.stopPropagation();
      setFocus(clip.filename, zone.dataset.focus);
    });
  });

  return card;
}

const grid = document.getElementById('grid');
for (const clip of clips) grid.appendChild(buildCard(clip));
updateStats();
</script>
</body>
</html>`;
}

// ─── Server ───────────────────────────────────────────────────────────────────

const server = createServer((req, res) => {
  // Save focus
  if (req.method === 'POST' && req.url === '/save') {
    let body = '';
    req.on('data', d => body += d);
    req.on('end', () => {
      try {
        const { filename, focus } = JSON.parse(body);
        if (!['top', 'center', 'bottom'].includes(focus)) throw new Error('invalid focus');
        const overrides = loadOverrides();
        overrides[filename] = focus;
        saveOverrides(overrides);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true }));
      } catch (e) {
        res.writeHead(400);
        res.end(e.message);
      }
    });
    return;
  }

  // Serve clips
  if (req.url.startsWith('/clips/')) {
    const relPath = decodeURIComponent(req.url.slice(7));
    const fullPath = resolve(CLIPS_ROOT, relPath);
    // Basic path traversal guard
    if (!fullPath.startsWith(CLIPS_ROOT)) { res.writeHead(403); res.end(); return; }
    if (!existsSync(fullPath)) { res.writeHead(404); res.end(); return; }
    const stat = statSync(fullPath);
    res.writeHead(200, {
      'Content-Type': 'video/mp4',
      'Content-Length': stat.size,
      'Accept-Ranges': 'bytes',
    });
    createReadStream(fullPath).pipe(res);
    return;
  }

  // Main page
  if (req.url === '/' || req.url === '') {
    const clips = getAllClips();
    const overrides = loadOverrides();
    const html = buildHtml(clips, overrides);
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(html);
    return;
  }

  res.writeHead(404);
  res.end();
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`Focus tagger running at http://localhost:${PORT}`);
  console.log('Open that URL in your browser.');
  console.log('Hover over a clip to play it, click top/middle/bottom to tag focus.');
  console.log('Changes save instantly to clips/focus-overrides.json\n');
  console.log('Press Ctrl+C to stop.');
});
